pillbox-web/pillbox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^timeset/', include('timeset.urls')),
    url(r'^admin/', admin.site.urls),
]

pillbox-web/timeset/urls.py
from django.conf.urls import url
from . import views

app_name = 'timeset'
urlpatterns = [
	url(r'^index$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<pk>[0-9]+)/setting$', views.SettingView.as_view(), name='setting'),
	url(r'^(?P<patient_id>[0-9]+)/set/$', views.set, name='set'),
    url(r'^$', views.Login),	
    url(r'^ip/$', views.setip, name='setip'),
]

pillbox-web/timeset/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Patient(models.Model):
	patient_name = models.CharField(max_length=200)
	def __str__(self):
		return self.patient_name

class Medicine(models.Model):
	patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
	medicine_text = models.CharField(max_length=200)
	time = models.TimeField()
	def __str__(self):
		return self.medicine_text
		
class Pi(models.Model):
	patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
	Pi_ip = models.GenericIPAddressField()
	def __str__(self):
		return self.Pi_ip

pillbox-web/timeset/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render

# Create your views here.
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from .models import Patient
from django.urls import reverse
from django.views import generic

global ip
from socket import *
class IndexView(generic.ListView):
	template_name = 'timeset/index.html'
	context_object_name = 'patient_list'
	def get_queryset(self):
		return Patient.objects.all()

class ResultsView(generic.DetailView):
	model = Patient
	template_name = 'timeset/results.html'

class SettingView(generic.DetailView):
	model = Patient
	template_name = 'timeset/setting.html'

def Login(request):
    return render(request, 'timeset/login.html')
    
def setip(request):
	global ip
	ip = request.META.get('REMOTE_ADDR')
	print ip
	return HttpResponse(ip) 

def set(request, patient_id):
	patient = get_object_or_404(Patient, pk=patient_id)
	for index, medicine in enumerate(patient.medicine_set.all()):
		s = "medicine"+str(index+1)
		medicine.time = request.POST[s]
		medicine.save()
		global ip
		HOST = ip
		print 'HOST', HOST
		PORT = 21567
		BUFSIZ = 1024
		ADDR = (HOST,PORT)
		print 'ADDR', ADDR
		tcpCliSock = socket(AF_INET,SOCK_STREAM)
		print 'tcpCliSock', tcpCliSock
		tcpCliSock.connect(ADDR)
		print 'connected'
		tcpCliSock.send(medicine.time)
		print 'finish'
	#message = tcpCliSock.recv(BUFSIZ)
	return HttpResponseRedirect(reverse('timeset:results', args=(patient.id,)))
	
#class PiOnline():

#def sendtime(request, patient_id):
	#pi_id = get_object_or_404(Pa)

pillbox-web/timeset/templates/timeset/detail.html
<h1>{{ patient.patient_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'timeset:setting' patient.id %}" method="post">
{% csrf_token %}
{% for medicine in patient.medicine_set.all %}
    <label for="medicine{{ forloop.counter }}">{{ medicine.medicine_text }}</label>
    <input type="text" name="medicine{{forloop.counter}}" id="medicine{{forloop.counter}}"/><br/>
{% endfor %}
<input type="submit" value="Submit" />
</form>

pillbox-web/timeset/templates/timeset/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Pill Box Demo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="http://ajax.htmlnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>
  <script>
    $(document).ready(function(){
        $("#Yichi").click(function(){
            $("#Patient_b").text("Yichi Zhang");
        });

        $("#Zheng").click(function(){
            $("#Patient_b").text("Zheng Zhang");
        });

        $("#Xiaoyu").click(function(){
            $("#Patient_b").text("Xiaoyu Zhou");
        });

        $("#Xiang").click(function(){
            $("#Patient_b").text("Xiang Li");
        });

        $("#Boyu").click(function(){
            $("#Patient_b").text("Boyu Liu");
        });
    });
</script>
</head>
<body>

<div class="container">
    <div style="font-family:verdana;padding:20px;border-radius:10px;border:10px solid #EE872A;">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h3>Pill Box 1.0</h3>
            <div class="tabbable" id="tabs-647325">


                <ul class="nav nav-tabs">
                    
                    <li class="active">
                         <a href="#panel-77062" data-toggle="tab">Review Reports</a>
                    </li>
                </ul>

                <div class="tab-content">

                    <div class="tab-pane active" id="panel-77062">
                        <p>
                            <h4>This is the eating reports of the patient: Xiaoyu Zhou</h4>
                            <div class="row clearfix">
                                <div class="col-md-8 column">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Number
                                                </th>
                                                <th>
                                                    Pill Name
                                                </th>
                                                <th>
                                                    Eat Time
                                                </th>
                                                <th>
                                                    Status
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr class="success">
                                                <td>
                                                    1
                                                </td>
                                                <td>
                                                    Norfloxacin
                                                </td>
                                                <td>
                                                    01/04/2017
                                                </td>
                                                <td>
                                                    Normal
                                                </td>
                                            </tr>
                                            <tr class="warning">
                                                <td>
                                                    2
                                                </td>
                                                <td>
                                                    Norfloxacin
                                                </td>
                                                <td>
                                                    01/05/2017
                                                </td>
                                                <td>
                                                    Not Eated
                                                </td>
                                            </tr>
                                            <tr class="warning">
                                                <td>
                                                    3
                                                </td>
                                                <td>
                                                    Norfloxacin
                                                </td>
                                                <td>
                                                    01/06/2017
                                                </td>
                                                <td>
                                                    Not Eated
                                                </td>
                                            </tr>
                                            <tr class="success">
                                                <td>
                                                    4
                                                </td>
                                                <td>
                                                    Norfloxacin
                                                </td>
                                                <td>
                                                    01/07/2017
                                                </td>
                                                <td>
                                                    Normal
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            
                                        
                                <div class="col-md-4 column">
                                    <div class="btn-group">
                                        <h3>Please select the patient:</h3>
                                        <button class="btn btn-default" id="Patient_b">Patients</button> <button data-toggle="dropdown" class="btn btn-info dropdown-toggle"><span class="caret"></span></button>
                                        <ul class="dropdown-menu">
                                            {% for patient in patient_list %}
                                                <li class="enabled" id="{{patient.patient_name}}"><a href="{% url 'timeset:results' patient.id %}">{{ patient.patient_name}}</a></li>
                                            {% endfor %}

                                            <li class="enabled" id="Yichi">
                                                 <a href="#Yichi">Yichi Zhang</a>
                                            </li>
                                            <li class="enabled" id="Xiaoyu">
                                                 <a href="#Xiaoyu">Xiaoyu Zhou</a>
                                            </li>
                                            <li class="enabled" id="Zheng">
                                                 <a href="#Zheng">Zheng Zhang</a>
                                            </li>
                                            <li class="enabled" id="Xiang">
                                                 <a href="#Xiang">Xiang Li</a>
                                            </li>
                                            <li class="enabled" id="Boyu">
                                                 <a href="#Boyu">Boyu Liu</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                            </div>

                        </p>
                    </div>


                </div>


            </div>
        </div>
    </div>
</div>

<!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- 包括所有已编译的插件 -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>

pillbox-web/timeset/templates/timeset/login.html
<!DOCTYPE html>
<html>
   <head>
      <title>Pill Box Login</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- 引入 Bootstrap -->
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
 
      <!-- HTML5 Shiv 和 Respond.js 用于让 IE8 支持 HTML5元素和媒体查询 -->
      <!-- 注意： 如果通过 file://  引入 Respond.js 文件，则该文件无法起效果 -->
      <!--[if lt IE 9]>
         <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
         <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
   </head>
   <body>
    </div>
        <div style="font-family:verdana;padding:20px;border-radius:10px;border:10px solid #EE872A;">
        <div class="container">
            
                <div class="row clearfix">
                  <div class="col-md-2 column">
                  </div>
                  <div class="col-md-8 column">
                    <div class="jumbotron">
                      <h1 class="text-center">
                        Welcome! Pill Box!
                      </h1>
                    </div>
                  </div>
                  <div class="col-md-2 column">
                  </div>
            </div>




            <div class="row clearfix">
              <div class="col-md-2 column">
              </div>
              <div class="col-md-8 column">
                <form class="form-horizontal" role="form">
                  <fieldset>
                    <legend>Log in:</legend>
                  <div class="form-group">
                     <label for="text" class="col-sm-2 control-label">UserName</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="userName" />
                    </div>
                  </div>
                  <div class="form-group">
                     <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-10">
                      <input type="password" class="form-control" id="inputPassword3" />
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <div class="checkbox">
                         <label><input type="checkbox" />Remember me</label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                       <button type="submit" class="btn btn-default" onclick=window.open("index")>Sign in</button>
                    </div>
                  </div>
                </fieldset>
                </form>
              </div>
              <div class="col-md-2 column">
              </div>
            </div>
            <div class="row clearfix">
              <div class="col-md-12 column">
              </div>
            </div>
          </div>
 
      <!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
      <script src="https://code.jquery.com/jquery.js"></script>
      <!-- 包括所有已编译的插件 -->
      <script src="js/bootstrap.min.js"></script>
   </body>
</html>

pillbox-web/timeset/templates/timeset/results.html
<!DOCTYPE html>
<html>
<head>
  <title>Pill Box Demo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="http://ajax.htmlnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>
</script>
</head>
<body>

<div class="container">
    <div style="font-family:verdana;padding:20px;border-radius:10px;border:10px solid #EE872A;">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h3>Pill Box 1.0</h3>
            <div class="tabbable" id="tabs-647325">


                <ul class="nav nav-tabs">
                    
                    <li class="active">
                         <a href="#panel-77062" data-toggle="tab">Review Setting</a>
                    </li>
                </ul>

                <div class="tab-content">

                    <div class="tab-pane active" id="panel-77062">
                        <p>
                            <h4>This is the eating reports of the patient: <strong>{{ patient.patient_name }}</strong></h4>
                            <br>
                            <div class="row clearfix">
                                <div class="col-md-8 column">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>
                                                    Pill Name
                                                </th>
                                                <th>
                                                    Eat Time
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for medicine in patient.medicine_set.all %}
                                            <tr class="success">
                                                <td>
                                                    {{ medicine.medicine_text }}
                                                </td>
                                                <td>
                                                    {{ medicine.time }}
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            
                                <div class="row clearfix">
                                    <div class="col-md-4 column">        
                                        <div class="jumbotron">
                                            <h4>
                                                Thank you for your attention!
                                            </h4>
                                            <hr>
                                                You patient keep on taking pills for five days!
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </p>
                    </div>


                </div>


            </div>
        </div>

        <div class="row clearfix">
            <div class="col-md-4 column">
            </div>
                <div class="col-md-4 column">
                    <strong><a href="{% url 'timeset:setting' patient.id %}" class="center">Set time</a> | <a href="{% url 'timeset:index' %}">Back to all patients</a></strong>
                </div>
            <div class="col-md-4 column">
            </div>
        </div>
    </div>
</div>


<!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- 包括所有已编译的插件 -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>

pillbox-web/timeset/templates/timeset/setting.html
<!DOCTYPE html>
<html>
<head>
  <title>Pill Box Demo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">  
  <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="http://ajax.htmlnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>
</script>
</head>
<body>

<div class="container">
    <div style="font-family:verdana;padding:20px;border-radius:10px;border:10px solid #EE872A;">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <h3>Pill Box 1.0</h3>
            <div class="tabbable" id="tabs-647325">


                <ul class="nav nav-tabs">
                    
                    <li class="active">
                         <a href="#panel-77062" data-toggle="tab">Setting</a>
                    </li>
                </ul>

                <div class="tab-content">

                    <div class="tab-pane active" id="panel-77062">
                        <p>
                            <h4>You are going to set the patient: <strong>{{ patient.patient_name }}</strong></h4>
                            <br>
                            <div class="row clearfix">
                                <div class="col-md-8 column">
                                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                                    <form action="{% url 'timeset:set' patient.id %}" method="post">
                                        {% csrf_token %}
                                        {% for medicine in patient.medicine_set.all %}
                                            <label for="medicine{{ forloop.counter }}">{{ medicine.medicine_text }}: </label>
                                            <input type="text" name="medicine{{forloop.counter}}" id="medicine{{forloop.counter}}"/><br/>
                                        {% endfor %}
                                        <input type="submit" value="Submit" />
                                    </form>
                                </div>
                            
                                <div class="row clearfix">
                                    <div class="col-md-4 column">        
                                        <div class="jumbotron">
                                            <h4>
                                                Thank you for your attention!
                                            </h4>
                                            <hr>
                                                You patient keep on taking pills for five days!
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </p>
                    </div>


                </div>


            </div>
        </div>

        <div class="row clearfix">
            <div class="col-md-4 column">
            </div>
                <div class="col-md-4 column">
                    <strong><a href="{% url 'timeset:setting' patient.id %}" class="center">Set time</a> | <a href="{% url 'timeset:index' %}">Back to all patients</a></strong>
                </div>
            <div class="col-md-4 column">
            </div>
        </div>
    </div>
</div>


<!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- 包括所有已编译的插件 -->
<script src="js/bootstrap.min.js"></script>
</body>
</html>